### ISSUE TITLE
Header anchors

### ISSUE THREAD

**Issue by danielgtaylor** [jonschlinkert/remarkable#122] opened 2014-12-18 07:31 UTC
Automatic header anchors/links like you see on GitHub and various other places would be a nice feature. For example:

![screen shot 2014-12-17 at 11 27 51 pm](https://cloud.githubusercontent.com/assets/106826/5484796/964fdce6-8644-11e4-89f4-e85dc661cd1b.png)

The link next to the header is https://github.com/jonschlinkert/remarkable#usage

It looks like it's possible to update the renderer rules, but the header close element has no information about the text content of the header and I'm concerned about completely overwriting such rules. Is it possible to support this feature out of the box or to provide some more information in the existing elements so that writing a custom renderer is easy?

**Comment by jeromegn** [comment] 2015-06-05 17:39
I would love that too.

Or pointers on how to create a plugin that would do that.

**Comment by KyleAMathews** [comment] 2015-06-07 23:02
:+1:

**Comment by dahjelle** [comment] 2015-10-21 20:10
If you have `toc = require('markdown-toc')` available (from [markdown-toc](https://www.npmjs.com/package/markdown-toc)), a simplistic version of this might be:

```
let md = new Remarkable().use(function(remarkable) {
  remarkable.renderer.rules.heading_open = function(tokens, idx) {
    return '<h' + tokens[idx].hLevel + ' id=' + toc.slugify(tokens[idx + 1].content) + '>';
  };
});
```

I've barely tested this, and it probably doesn't handle nested headings particularly well or duplicated heading contents or any number of other edge cases, but it's a start.

**Comment by danielgtaylor** [comment] 2015-10-22 23:57
For the record, I wound up using [markdown-it](https://github.com/markdown-it/markdown-it) and the [markdown-it-anchor](https://github.com/valeriangalliat/markdown-it-anchor) plugin with a custom `slugify()` function (that takes into account other existing IDs on the page). It works well and is worth a try if you are waiting for this feature!

**Comment by jonschlinkert** [comment] 2015-10-23 00:45
>  it probably doesn't handle nested headings particularly well 

like this? https://github.com/assemble/assemble-core#assemble-core- 

> or duplicated heading contents or any number of other edge cases, but it's a start.

I'm sure there are edge cases, but fwiw I'm using markdown-toc on hundreds of projects and it works consistently well. (also fwiw you might see a few projects where the formatting is messed up, but it was probably caused by the markdown formatter I had at the time, not the toc). 

closing since not technically an issue, but... I will plan on creating an example and I'll link it here when I have something to show

**Closed by jonschlinkert** 2015-10-23 00:45 UTC
Labels: request
